# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerCompose@0
  displayName: 'Run a Docker Compose command'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: 'docker-compose.yml'
    dockerComposeFileArgs: 'CM_REG_LOC=779583083558.dkr.ecr.us-gov-west-1.amazonaws.com'
    dockerComposeCommand: build

- task: AmazonWebServices.aws-vsts-tools.ECRPushImage.ECRPushImage@1
  displayName: 'Push Image: '
  inputs:
    awsCredentials: 'AWS Connection'
    regionName: 'us-gov-west-1'
    sourceImageName: '779583083558.dkr.ecr.us-gov-west-1.amazonaws.com/open-semantic-search-poc'
    repositoryName: 'open-semantic-search-poc'
    pushTag: '$(Build.BuildId)'
    autoCreateRepository: true

- task: CopyFiles@2
  displayName: 'Copy Files to: output/'
  inputs:
    Contents: |
     docker-compose.yml
     docker-compose.*.yml
     docker-entrypoint.sh
    TargetFolder: output/

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: source'
  inputs:
    PathtoPublish: output/
    ArtifactName: source



